#!/data/data/com.termux/files/usr/bin/bash
export PATH=/data/data/com.termux/files/usr/bin:$PATH

termux-wake-lock
sleep 15

curl -sL https://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@raw.githubusercontent.com/tinhpr9/Aotscript/refs/heads/main/agent -o /sdcard/Download/Agent_Core.py
python /sdcard/Download/Agent_Core.py > /sdcard/Download/Agent_Log.txt 2>&1 &
